[config]
google_address_validator_api_key = "google_address_validator_api_key"
project_id = "Google_bigQuery_project_id"
api_base_url = "https://api.base.url"
loctracker_api_password = "loctracker_api_password"
loctracker_api_username = "loctracker_api_username"
gemini_api_key = "gemini_api_key"
few_shot_examples_path = "few_shot_examples/examples.json"
bigquery_service_account_json = '''
{
 Big Query Service Account JSON body here
}
'''